version: "3.1"

services:
  confluence:
    image: atlassian/confluence-server
    restart: always
    volumes:
      - ./confluence:/var/atlassian/application-data/confluence
    ports:
      - 80:8090
      - 8091:8091

  db:
    image: postgres:9.6
    container_name: postgres
    volumes:
      - ./postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=confluencedb
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=confluencedb
    ports:
      - 5432:5432
